language: go

go:
- 1.16

os:
  - linux
  - osx
  - windows

script:
  - go build cli/logh.go
  - go test -race -coverprofile=coverage.txt -covermode=atomic

before_deploy:
  - mv logh "logh-$TRAVIS_TAG-$TRAVIS_OS_NAME"

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: d1FWoHXqXw/WjtzWWyvGQLtulqNW7pnD1r+Rzonlsvk+oDajiUCPN5A1uJAqdpiEej7hXO2rzqsud1k8utNqg3u3ym0fvUBUfdQaqX4p3IZS/ql4Fjw3mizRFl1WZYff3MKKR3Ylcm8Is1vQVzqKnrliSlWx48a/M35sZ2Q7h4WJnb44/93YY+2J0fj4evzn4MGvMPoKs2u6mYZjLhqy8z57JcxsZLqHdVELsOmuXsd2WP3eQFjijwnw6tsAUocrkCUIixzfn24pZEzsZC+14LSmlb0HjxXAG5upuei3sBbS8nVWFXy9arRDv1LN3ubtZkVBJ/PPq/T3PccEGZLUdU5tt8bVowiVy4FCmcOxlYwoKEDM6M6gG0jgaqg3VrNwJ9yK64p0JNZprROWMfdcgN4O6QTG7BGwgg4pt+h/KraW3LPScXISVuFR1IzQYj75eLUnw2NCPO6zsluZP8/5x2ptz9vE8Dz836O4moBLnRXR/inbBY4o9OymptO5iI3GxfkaKnlcH6dWWHSTpnAQTUHDfn4SSnvsaVeXYXgk0pJeGavCWlnHKL+3Cezmp+OoB/kDGIt8dC1bslNxynXI+HTsP+5vu7/M0Osucu4Q5klHJ87CRRBCUhIeeRls/oeJg24b44AVTY+7W1Q7RM/crz83vkYs0pOrTtR4E+Y+CBM=
  file_glob: true
  file:
    - logh-*
  on:
    repo: haroflow/logh
    tags: true
    all_branches: true
